import type { ServerBuild } from '@remix-run/cloudflare';
import { createPagesFunctionHandler } from '@remix-run/cloudflare-pages';

export const onRequest: PagesFunction = async (context) => {
  // `build/server` is generated by `pnpm run build`; it intentionally does not
  // exist in a fresh checkout, hence the suppression for the static types.
  // @ts-ignore -- generated at build time
  const serverBuild = (await import('../build/server')) as unknown as ServerBuild;

  const handler = createPagesFunctionHandler({
    build: serverBuild,
  });

  return handler(context);
};
